id: P003006
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:33:55.085380
source_metadata:
  id: bdr:W3CN5111
  title: རྗེ་བཙུན་སྒྲོལ་མའི་བསྟོད་པ་དང་ཕན་ཡོན་གྱི་འགྲེལ་པ།
  author: ''
  volumes:
    cb39cc1517f549e38de78685bfc97040:
      image_group_id: I3CN5113
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
