id: I6226DC18
legacy_id: P003006
ocr_import_info:
  bdrc_scan_id: W3CN5111
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T05:08:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:58:20.655730+00:00'
last_modified: 2022-08-27 19:58:28.450630
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5111
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5111
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྗེ་བཙུན་སྒྲོལ་མའི་བསྟོད་པ་དང་ཕན་ཡོན་གྱི་འགྲེལ་པ།
  author: མཁན་ཆེན་བསྟན་པ་རབ་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.9593172684488316
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I3CN5113:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5113
      total_pages: 114
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5113.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9593172684488316
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
